#!/bin/bash

mkdir -p /etc/systemd/user/niri.service.wants/
ln -s /etc/systemd/user/eww.service /etc/systemd/user/niri.service.wants/
ln -s /etc/systemd/user/eww-open@.service /etc/systemd/user/niri.service.wants/eww-open@background.service
ln -s /etc/systemd/user/eww-open@.service /etc/systemd/user/niri.service.wants/eww-open@window-workspaces.service

ln -s /etc/systemd/user/xwayland-satellite.service /etc/systemd/user/niri.service.wants/

fc-cache -fv

chmod +x /usr/local/bin/niri-session
chmod +x /usr/local/bin/rudeus-config

echo /usr/bin/fish | sudo tee -a /etc/shells
chsh -s /usr/bin/fish
