stow:
    stow -t $HOME alacritty
    stow -t $HOME eww
    stow -t $HOME fish

    stow -t $HOME niri

    stow -t $HOME starship
    stow -t $HOME wofi
    stow -t $HOME yazi
    stow -t $HOME zed

unstow:
    stow -t $HOME -D alacritty
    stow -t $HOME -D eww
    stow -t $HOME -D fish

    stow -t $HOME -D niri

    stow -t $HOME -D starship
    stow -t $HOME -D wofi
    stow -t $HOME -D yazi
    stow -t $HOME -D zed
